name: Terraform AWS Infrastructure

on:
  push:
    branches:
      - main 
    paths:
      - 'jenkins-project/**'  # Trigger when files in the jenkins-project directory change
  workflow_dispatch:  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Modify to your AWS region

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.4.6'  # Use the appropriate Terraform version

    - name: Initialize Terraform
      run: |
        cd jenkins-project
        terraform init

    - name: Validate Terraform
      run: |
        cd jenkins-project
        terraform validate

    - name: Apply Terraform Changes
      run: |
        cd jenkins-project
        terraform apply -auto-approve
